apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: ehcos-bpm-dep
  labels:
    suite: ehcos
    app: bpm
spec:
  replicas: 2
  template:
    metadata:
      labels:
        suite: ehcos
        app: bpm
    spec:
      containers:
      - name: bpm-module
        image: pocehcoscloudcr-on.azurecr.io/bpm-module:v4.3-cloud
        imagePullPolicy: Always
        resources:
          requests:
            memory: "1Gi"
            cpu: "400m"
          limits:
            memory: "1Gi"
        readinessProbe:
          httpGet:
            path: /ehcs-workflow-server-jbpm
            port: 8080
            scheme: HTTP
          timeoutSeconds: 2
          periodSeconds: 10
        livenessProbe:
          httpGet:
            path: /ehcs-workflow-server-jbpm
            port: 8080
            scheme: HTTP
          initialDelaySeconds: 60
          timeoutSeconds: 2
          periodSeconds: 10
        env:
          - name: PROPS_PATH
            value: "/tomcat/properties/"
          - name: BPM_PATH_SOCIALWORK
            value: "http://52.169.0.95/ehCS-ui/ws"
          - name: BPM_PATH_ACCORD
            value: "http://52.169.0.95/ehAccord-ui/ws"
          - name: BPM_PATH_CLINIC
            value: "http://52.169.0.95/ehCS-ui/ws"
          - name: BPM_PATH_HIS
            value: "http://52.169.0.95/ehHIS-ui/ws"
          - name: BPM_PATH_CEX
            value: "http://52.169.0.95/ehCS-ui/ws"
          - name: MULTITENANCY_ENABLED
            value: "true"
          - name: ETCD_SERVER_URL
            value: "http://40.69.65.71:2379"
          - name: ETCD_SERVER_TENANTSPATH
            value: "tenants"
          - name: JNDI_NAME
            value: "java:comp/env/jdbc/ehCOSDatasourceBPM"            
          - name: PERSISTENCE_DIALECT
            value: "com.everis.ehcos.framework.database.azure.AzureSQLDialect"
          - name: PERSISTENCE_DATABASE
            value: "SQL_SERVER"            
          - name: JDBC_DATABASENAME
            value: "hospital1"
          - name: JDBC_DRIVERCLASSNAME 
            value: "com.microsoft.sqlserver.jdbc.SQLServerDriver"
          - name: JDBC_USERNAME 
            value: "JBPM"
          - name: JDBC_PASSWORD
            value: "ehCOS2014"
          - name: JDBC_PORTNUMBER
            value: "1433"            
          - name: JDBC_SERVERNAME
            value: "ehcosazuredb.database.windows.net"
          - name: JDBC_VALIDATIONQUERY
            value: "Select 1"
        ports:
        - containerPort: 8080
      imagePullSecrets:
        - name: ehcoscrsecret
