apiVersion: v1
kind: Secret
metadata:
  name: azure-staccount-secret
  labels:
    suite: ehcos
type: Opaque
data:
  azurestorageaccountname: ZWhjb3NzdGFjY291bnQy
  azurestorageaccountkey: TC81aTFDMG9vS1IvVlNvKzcxSjdNbjNIaFgwenVoOUZWLzJ1TXB4UzhDd1hHeTZTNUJiNi9aTTVkbVRLN3VoTjlPVEF5MlRSeHljeW1tVGVUSXI1M1E9PQ== 

